### ISSUE TITLE
Automate the configuration of UI dev endpoint

### ISSUE THREAD

**Issue by dashinay** [ActoKids/devops#31] opened 2019-02-25 08:56 UTC
I have to collaborate with the UI team on automating a process of creating an endpoint and issue a certificate. The UI team must present a ready endpoint and instruction on how to complete the task so I can proceed to automate it with cli.
Each assigned member from both teams must review ones work and give feedback.

Actual time: 8
Expected time: 6

**Comment by bmenaz** [comment] 2019-03-07 00:30
Setting up automation using AWS CLI:

- Create or update an alias record set in Route53 for a domain alias www-dev.edusite.com.
- Connect the record www-dev.2edusite.com to development environment s3 bucket.

PR: https://github.com/ActoKids/devops/pull/43

[Wiki](https://github.com/ActoKids/devops/wiki/Automation-for-Development-endpoint-of-team-UI)

Reviews and tests:
- For this task i have been assigned to work with Phu for team UI. Tested his endpoints www-dev.2edusite.com and it is working correctly. The SSL is attached to the endpoint and the endpoint is secure.
- I tested Dawit's script and it was running without issues. Since there was already a cloudfront distribution it got the domain name from it and used it to create a record sets in Route53

- My script has been tested by Dawit and Anar and they have confirmed the functionality of the script, it functions well and creates a route 53 record set for dev environment endpoint. Pull request has been approved.

Bugs fixed:
https://github.com/ActoKids/web-crawler/issues/16

Bugs created:
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/98

**Closed as completed** 2019-03-13 12:59 UTC
Labels: DevOps team, Sprint 4
