### ISSUE TITLE
Travis CI for Crawler (prod) (2 lambdas)

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#48] opened 2019-03-07 04:06 UTC
Task is to finalize the Travis Ci production pipeline for Web-Crawler team repository and make sure it is error free.
Due to the changes in structure production environment is no longer deployed into one AWS Lambda but into three separate Lambdas.

Actual time: 7 hr
Estimated time: 4 hr

**Comment by bmenaz** [comment] 2019-03-18 20:18
I have completed the deployment of production environment crawler, tested each function to be deployed, and confirmed it deploys properly. For the deployment, I have created three functions 1) OFAScraper_prod 2) ShadowSealScraper_prod 3) GoogleCalanderScraper_prod and one s3 bucket to host ofa package. S3 bucket has been created because Michael has informed me that ofa scraper is too large (I have also tested it) to be deployed into the Lambda directly, so it needs to be hosted on s3 bucket where Lambda would get the package from. 

PR: https://github.com/ActoKids/web-crawler/pull/25
Test build: https://travis-ci.org/ActoKids/web-crawler/builds/508055224
WIKI: https://github.com/ActoKids/web-crawler/wiki/Travis-CI
BUG: https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/117
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/121

Review I have given and gotten:
I have worked with Michael to test the Ci prod pipeline delivery and with his feedback and the travis ci reports was able to make it fully working. Michael has given his feedback and approved the pr.
The pr has also been reviewed by Shota and approved to go into the dev.

**Comment by LyndonP** [comment] 2019-03-20 23:26
Verified that the code works. Closing issue.

**Closed as completed by LyndonP** 2019-03-20 23:26 UTC
Labels: DevOps team, Sprint 5
